"""Create the Post Table

Revision ID: 185af976df10
Revises: 84e26ba635b0
Create Date: 2025-06-04 14:15:04.279072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185af976df10'
down_revision = '84e26ba635b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.String(length=350), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
